### ISSUE TITLE
Parsing error: Unexpected token  :

### ISSUE THREAD

**Issue by nadeemja** [guigrpa/storyboard#12]
Error when using: import { mainStory: story } from 'storyboard';

How else do I use this?

**Comment by guigrpa** [comment]
Which version are you using? I'll try to reproduce it, but that's the normal way, yes

**Comment by guigrpa** [comment]
Could you also please copy the whole error message?

**Comment by guigrpa** [comment]
If you are not using Babel, just use:

```js
var story = require('storyboard').mainStory;
```

Or in CoffeeScript:

```coffee
{ mainStory: story } = require 'storyboard';
```

Let me know if that worked for you.

**Comment by nadeemja** [comment]
That was the entire error, as far as I can recall. Is there some specific info you're missing? 

I'm using MeteorJS, which implements ES6 using the ecmascript package.
https://github.com/meteor/meteor/tree/devel/packages/ecmascript

I've not had similar issues with other non-meteor npm packages.

Thanks for the suggestions, btw, will try them out. 

PS. I couldn't figure out if storyboard can be configured as a general catch-all logger, without one having to inject calls to it in specific places. Is this possible?

**Comment by guigrpa** [comment]
Did you succeed with the suggestions I gave you?

**Comment by guigrpa** [comment]
Regarding Storyboard as "catch-all logger", you may want to have a look at [this issue](https://github.com/guigrpa/storyboard/issues/11).

**Comment by guigrpa** [comment]
Closing this now. Please reopen if the solution is not sufficient
