### ISSUE TITLE
Recieving logs by another websocket client

### ISSUE THREAD

**Issue by Nic2012** [guigrpa/storyboard#13]
For example in my node app is declared:
```javascript
var story = require("storyboard");
var wsServer = require("storyboard/lib/listeners/wsServer");
const options = {
  port: 4711
};
story.addListener(wsServer,options);
```
By ```story.mainStory.info("test", "something");``` I can watch it in chrome browser using dev tools on port 4711.

Now I want to see it on a simple webpage, too. E.g. I open a websocket client on same port:
```
<script src="socket.io.js"></script>
<script language="javascript" type="text/javascript">
	function setup() {
		var logger = document.getElementById("logger");

		var hostname = window.location.host;
		if (hostname=='') hostname = 'localhost';
		hostname = 'http://' + hostname + ':4711';
		
		var socket = io.connect(hostname);
		socket.on('info',
				function(data){
					logger.textContent += '\ninfo';
					if (data) logger.textContent += '\n\t' + data;
				});
	}								
</script>
...
<body bgcolor="white" onload="setup()">
	<pre id="logger"></pre>
</body>
```
But this doesnt work, I assume each message is broadcasted from storyboard to clients. So what is missing in my code to get the messages also in my page?

Best regrads,
Nic

**Comment by guigrpa** [comment]
I believe your problem derives from the [same-origin policy](https://en.wikipedia.org/wiki/Same-origin_policy). I don't know if you are just opening your HTML *file* above directly in your browser (a `file:` URL) or through a web server (an `http:` URL served through e.g. port `80`), but in any case you cannot open a websocket on port 4711 if your page (and its embedded script) loads from somewhere else. This is an important limitation put in place by browsers to avoid all kind of security threats.

**Comment by Nic2012** [comment]
Webpage is hosted by an Apache webserver, the port 4711 was an example. BTW,
I found the solution:
Websocket client has to be connected to the right namespace, too ;)
```
hostname = 'http://' + hostname + ':' + port + '/STORYBOARD';
```
And it instead of listening to an incoming info or message, it has listen to MSG event:
```
	socket.on('MSG',
			function(data){
			});
```
Works fine in e.g. Firefox browser and returns after some adjustments:
```
2016-05-16T17:13:32.239Z: Connect
2016-05-16T17:13:33.710Z: usb-detection.js	INFO	add usb
	[
	"locationId: \u001b[34m\u001b[1m0\u001b[22m\u001b[39m",
	"vendorId: \u001b[34m\u001b[1m2316\u001b[22m\u001b[39m",
	"productId: \u001b[34m\u001b[1m4096\u001b[22m\u001b[39m",
	"deviceName: \u001b[33m\u001b[1m'USB_DISK'\u001b[22m\u001b[39m",
	"manufacturer: \u001b[33m\u001b[1m'SMI_Corporation'\u001b[22m\u001b[39m",
	"serialNumber: \u001b[33m\u001b[1m''\u001b[22m\u001b[39m",
	"deviceAddress: \u001b[34m\u001b[1m0\u001b[22m\u001b[39m"
]
2016-05-16T17:13:52.557Z: Disconnect: transport close
```
Is it possible to disable or remove chalk color codes, otherwise the array cannnot be JSON.stringify?

Best regards,
Nicolas

**Comment by guigrpa** [comment]
You can use the function `getStyledSegments()` from `src/gral/ansiColors`. It returns an object with the various segments and style attributes, which you can use to build your own HTML (just as the Storyboard DevTools does) or just strip it from all style info.

In any case, why not simply use the Storyboard DevTools? Is it because it's limited to Chrome (for the time being at least)?

**Comment by Nic2012** [comment]
Why should I use a proprietary utility that can only be used with Chrome desktop version? When a simple webpage is easy to create and returning same information but on many browsers.
BTW y tool cannot be installed on Chrome mobile on Android at least.

**Comment by guigrpa** [comment]
The DevTools provide you (hopefully) with a better user experience. In any case, I'm glad that you managed to get it working with a simple page as well.
