### ISSUE TITLE
Forget items from leaves of tree upwards

### ISSUE THREAD

**Issue by masaeedu** [guigrpa/storyboard#23]
When the chrome extension starts forgetting items due to the predefined limit, it often starts with the top level parent stories that provide structure to the rest of what's going on. This usually results in nonsensical, confusing output.

When stuff is being forgotten, it should start with the log items from the leaf stories (say, an even selection of the oldest log items from every leaf story). Only once a story has no more children should it be deleted.

**Comment by guigrpa** [comment]
Hi, and thanks for the report!

Could you maybe share some steps to reproduce, or maybe screenshots of what you mean? Even better: maybe you could consider adding a failing test to the suite? In principle (see [this test](https://github.com/guigrpa/storyboard/blob/bf85f7ec0f6455aa3b24add982ee70773ce6cbff/packages/storyboard-extension-chrome/src/reducers/__tests__/12-storiesReducer.test.js#L78)), the *forgetting algorithm* should work just as you describe…

**Comment by guigrpa** [comment]
Closed due to inactivity. Please reopen if the problem comes back.
