### ISSUE TITLE
Demo is down.

### ISSUE THREAD

**Issue by giodamelio** [guigrpa/storyboard#24]
FYI, the [demo](https://storyboard-bhibtchlhy.now.sh/) is currently returning a 502.

**Comment by guigrpa** [comment]
Thanks for reporting!

I thought I had removed the link to that demo. Where did you get it from? Maybe from http://guigrpa.github.io/storyboard/? Then sorry, that page is obsolete and I'll delete it now.

**Comment by guigrpa** [comment]
I think that there *should* be an online demo, but don't have the time right now to deploy it!

**Comment by guigrpa** [comment]
Done, I replaced the specially-formatted-and-maybe-somewhat-old docs with a redirect. Sorry for that!
