### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by RobertWHurst** [guigrpa/storyboard#26]
Are there any plans to add typescript definitions?

I quite like this lib. I'd love to use it in my typescript projects.

**Comment by guigrpa** [comment]
I don't use typescript myself (yet). So feel free to submit a PR for this! The API should not be complex to model.

**Comment by andreialecu** [comment]
I see that there are flow types, they could be converted to typescript types pretty easily as well.

This project looks really promising, but also a bit stale. The addition of typescript support could do wonders for adoption.

Is maintenance still being planned/done?
