### ISSUE TITLE
Heroku app is down

### ISSUE THREAD

**Issue by winkler1** [guigrpa/storyboard#4]
This looks really interesting! I run react.rocks, looks like a great addition -- unfortunately, http://storyboard-demo.herokuapp.com/ is down at the moment?

**Comment by guigrpa** [comment]
I'm afraid it's seen a lot of traffic lately, and the app runs on the free Heroku tier (up to 18 hours of a 24-hour period). Please try again later, when the dyno wakes up from its sleep :smile: 

I'm closing this issue now, since I'm currently not considering upgrading to a paid tier.

**Comment by guigrpa** [comment]
On second thought, I've just upgraded to the lowest priced tier. It's not so much what they ask for, and it's no longer showing that nasty error message. Feel free to check it back.

**Comment by winkler1** [comment]
Looks great, thanks!
